spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:./test-db'
  jpa:
    hibernate:
      ddl-auto: validate
  auth-server-url: 'http://localhost:8180'
  realm: 'test'
  resource: 'test'
  public-client: true
